### PR TITLE
fix versions and links

### PR DESCRIPTION
**Pull request by mppfiles**

### CODE REVIEW

**Comment by mppfiles** [comment]
It's a shame that it's not possible to search in Maven Central by groupId + version, regardless of artifactID. Maybe would be better to make separate download links pointing to more direct results in Maven pages...

**Comment by ipolevoy** [comment]
Search provides a list  of releases and even dates: 
https://search.maven.org/search?q=activejdbc

**Comment by ipolevoy** [comment]
Selection_738

**Comment by ipolevoy** [comment]
https://search.maven.org/search?q=g:org.javalite%20v:2.3.1-j8

**Comment by mppfiles** [comment]
Awesome! will send another PR then with updated links! :smile:

**Pull request merged**
